### PR TITLE
minor refactoring

### PR DESCRIPTION
**Pull request by c0nrad**
Just some minor refactoring of the code for cleanliness

### CODE REVIEW

**Comment by struct** [comment]
This would have a negative effect on performance and my overall mood. Denied.

**Comment by jfalken** [comment]
Please consider re opening this. This adds a much cleaner and simpler interface

**Comment by vcarl** [comment]
+1 new interface is more webscale for my Go microservice framework API

**Comment by struct** [comment]
Please benchmark this for comparison and report back.

**Comment by c0nrad** [comment]
I'm happy to report Golang is still webscale.

https://notr-bucket.s3.amazonaws.com/911a368e-f8c2-48b5-8b0c-ea678f994d71

**Pull request closed without merging**
